### ISSUE TITLE
Fatal error while compiling templates

### ISSUE THREAD

**Issue by kubarazny** [alwaysblank/blade-generate#4]
I'm trying to compile blade templates in Sage theme, but I got an error:

```
Finding files...
PHP Fatal error:  Uncaught Error: Call to undefined function App\sage() in /home/vagrant/.wp-cli/packages/vendor/alwaysblank/blade-generate/command.php:92
Stack trace:
#0 [internal function]: BladeCommand->compile(Array, Array)
#1 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(89): call_user_func(Array, Array, Array)
#2 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#3 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(425): call_user_func(Object(Closure), Array, Array)
#4 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(365): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#5 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(388): WP_CLI\Runner->run_command(Array, Array)
#6 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1113): WP_CLI\Runner->_run_command_and_exit()
#7 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/Launc in /home/vagrant/.wp-cli/packages/vendor/alwaysblank/blade-generate/command.php on line 92
Fatal error: Uncaught Error: Call to undefined function App\sage() in /home/vagrant/.wp-cli/packages/vendor/alwaysblank/blade-generate/command.php:92
Stack trace:
#0 [internal function]: BladeCommand->compile(Array, Array)
#1 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(89): call_user_func(Array, Array, Array)
#2 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#3 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(425): call_user_func(Object(Closure), Array, Array)
#4 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(365): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#5 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(388): WP_CLI\Runner->run_command(Array, Array)
#6 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1113): WP_CLI\Runner->_run_command_and_exit()
#7 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/Launc in /home/vagrant/.wp-cli/packages/vendor/alwaysblank/blade-generate/command.php on line 92
```

**Comment by alwaysblank** [comment]
Sorry for the delayed response!

I'm unable to replicate this error. Can you provide more information on your environment, and the context in which the error appears? Please consult the bug reporting guidelines: https://github.com/alwaysblank/blade-generate#reporting-a-bug

**Comment by oquirozm** [comment]
I too encountered the bug @alwaysblank. It happened after I installed wp-cli on a one-click WordPress install on DigitalOcean.

My environment is:
- Sage 9.0.9
- WordPress 5.2.2.
- PHP 7.2
- Ubuntu 18.02

I've used `blade generate` before and the only thing I could think of that changed between my previous projects and this one is the PHP and WordPress' versions.

Here's a copy of the error after I run `wp blade clear --allow-root`:
```
PHP Fatal error:  Uncaught Error: Call to undefined function App\sage() in /root/.wp-cli/packages/vendor/alwaysblank/blade-generate/command.php:150
Stack trace:
#0 [internal function]: BladeCommand->clear(Array, Array)
#1 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(98): call_user_func(Array, Array, Array)
#2 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#3 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(451): call_user_func(Object(Closure), Array, Array)
#4 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(371): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#5 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(394): WP_CLI\Runner->run_command(Array, Array)
#6 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1132): WP_CLI\Runner->run_command_and_exit()
#7 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.ph in /root/.wp-cli/packages/vendor/alwaysblank/blade-generate/command.php on line 150
Fatal error: Uncaught Error: Call to undefined function App\sage() in /root/.wp-cli/packages/vendor/alwaysblank/blade-generate/command.php:150
Stack trace:
#0 [internal function]: BladeCommand->clear(Array, Array)
#1 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php(98): call_user_func(Array, Array, Array)
#2 [internal function]: WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}(Array, Array)
#3 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php(451): call_user_func(Object(Closure), Array, Array)
#4 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(371): WP_CLI\Dispatcher\Subcommand->invoke(Array, Array, Array)
#5 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(394): WP_CLI\Runner->run_command(Array, Array)
#6 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1132): WP_CLI\Runner->run_command_and_exit()
#7 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.ph in /root/.wp-cli/packages/vendor/alwaysblank/blade-generate/command.php on line 150
Error: The site is experiencing technical difficulties.
```

**Comment by oquirozm** [comment]
Ok, I could make the error go away by doing the following:
- Make sure `composer` is installed (it wasn't in my case)
- Make sure there are already some blade templates in the project created after the installation of sage theme.

After I did these 2, everything worked correctly.

**Comment by vedammc** [comment]
I think this error happens when you don't activate the Sage theme.

**Comment by alwaysblank** [comment]
Hi folks,

Thanks for your research, and sorry it's taken me so long to respond! I've tagged a new release (https://github.com/alwaysblank/blade-generate/releases/tag/1.2) that adds some language to the README mentioning that you must install and activate Sage 9 to use the plugin, as well as a small check in the plugin itself to make sure the functionality it needs from Sage is available before it tries to use that functionality.

This should resolve the issue, but if you feel differently please let me know and I'll re-open the issue.
